version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    networks:
      - pomodoro
networks:
  pomodoro: